-- MySQL Script generated by MySQL Workbench
-- Tue Dec  7 17:20:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fastsociety
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fastsociety` ;

-- -----------------------------------------------------
-- Schema fastsociety
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fastsociety` DEFAULT CHARACTER SET utf8 ;
USE `fastsociety` ;

-- -----------------------------------------------------
-- Table `fastsociety`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsociety`.`User` ;

CREATE TABLE IF NOT EXISTS `fastsociety`.`User` (
  `id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `image` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastsociety`.`Society`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsociety`.`Society` ;

CREATE TABLE IF NOT EXISTS `fastsociety`.`Society` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(250) NULL,
  `email` VARCHAR(45) NULL,
  `totalFollows` VARCHAR(45) NOT NULL DEFAULT 0,
  `image` VARCHAR(255) NULL,
  `head_id` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Society_User_idx` (`head_id` ASC) VISIBLE,
  CONSTRAINT `fk_Society_User`
    FOREIGN KEY (`head_id`)
    REFERENCES `fastsociety`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastsociety`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsociety`.`Role` ;

CREATE TABLE IF NOT EXISTS `fastsociety`.`Role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `createPost` TINYINT NULL DEFAULT 0,
  `createEvent` TINYINT NULL DEFAULT 0,
  `deletePost` TINYINT NULL DEFAULT 0,
  `deleteEvent` TINYINT NULL DEFAULT 0,
  `Society_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Role_Society1_idx` (`Society_id` ASC) VISIBLE,
  CONSTRAINT `fk_Role_Society1`
    FOREIGN KEY (`Society_id`)
    REFERENCES `fastsociety`.`Society` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastsociety`.`Registration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsociety`.`Registration` ;

CREATE TABLE IF NOT EXISTS `fastsociety`.`Registration` (
  `User_id` VARCHAR(50) NOT NULL,
  `Society_id` INT NOT NULL,
  `Role_id` INT NULL,
  `joinDate` DATE NULL DEFAULT (CURRENT_DATE),
  PRIMARY KEY (`User_id`, `Society_id`),
  INDEX `fk_Registration_Role1_idx` (`Role_id` ASC) VISIBLE,
  INDEX `fk_Registration_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Registration_Society1_idx` (`Society_id` ASC) VISIBLE,
  CONSTRAINT `fk_Registration_Role1`
    FOREIGN KEY (`Role_id`)
    REFERENCES `fastsociety`.`Role` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registration_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `fastsociety`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registration_Society1`
    FOREIGN KEY (`Society_id`)
    REFERENCES `fastsociety`.`Society` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastsociety`.`Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsociety`.`Event` ;

CREATE TABLE IF NOT EXISTS `fastsociety`.`Event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `venue` VARCHAR(45) NULL,
  `textContent` VARCHAR(1000) NOT NULL,
  `createdOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `startTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  `image` VARCHAR(255) NULL,
  `User_id` VARCHAR(50) NULL,
  `Society_id` INT NULL,
  INDEX `fk_Event_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Event_Society1_idx` (`Society_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Event_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `fastsociety`.`User` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Event_Society1`
    FOREIGN KEY (`Society_id`)
    REFERENCES `fastsociety`.`Society` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastsociety`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsociety`.`Post` ;

CREATE TABLE IF NOT EXISTS `fastsociety`.`Post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `textContent` VARCHAR(300) NULL,
  `createdOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `image` VARCHAR(255) NULL,
  `User_id` VARCHAR(50) NOT NULL,
  `Event_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Post_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Post_Event1_idx` (`Event_id` ASC) VISIBLE,
  CONSTRAINT `fk_Post_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `fastsociety`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_Event1`
    FOREIGN KEY (`Event_id`)
    REFERENCES `fastsociety`.`Event` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastsociety`.`Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsociety`.`Message` ;

CREATE TABLE IF NOT EXISTS `fastsociety`.`Message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `textContent` VARCHAR(45) NOT NULL,
  `createdOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `User_id` VARCHAR(50) NOT NULL,
  `Society_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Message_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Message_Society1_idx` (`Society_id` ASC) VISIBLE,
  CONSTRAINT `fk_Message_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `fastsociety`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_Society1`
    FOREIGN KEY (`Society_id`)
    REFERENCES `fastsociety`.`Society` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastsociety`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsociety`.`Comment` ;

CREATE TABLE IF NOT EXISTS `fastsociety`.`Comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `textContent` VARCHAR(45) NOT NULL,
  `createdOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `User_id` VARCHAR(50) NOT NULL,
  `Event_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comment_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Comment_Event1_idx` (`Event_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `fastsociety`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Event1`
    FOREIGN KEY (`Event_id`)
    REFERENCES `fastsociety`.`Event` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastsociety`.`Review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsociety`.`Review` ;

CREATE TABLE IF NOT EXISTS `fastsociety`.`Review` (
  `User_id` VARCHAR(50) NOT NULL,
  `Event_id` INT NOT NULL,
  `stars` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`User_id`, `Event_id`),
  INDEX `fk_Post_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Post_Event1_idx` (`Event_id` ASC) VISIBLE,
  CONSTRAINT `fk_Post_User10`
    FOREIGN KEY (`User_id`)
    REFERENCES `fastsociety`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_Event10`
    FOREIGN KEY (`Event_id`)
    REFERENCES `fastsociety`.`Event` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
